### ISSUE TITLE
Should not use cached lifecycle commands for read or otherwise

### ISSUE THREAD

**Issue by mrzor** [scottwinkler/terraform-provider-shell#59]
Greetings!

I believe I stumbled upon a bug. I changed my lifecycle commands on a shell_script resource (was moving the script around), and couldn't even plan after that because the read would fail - I had to `terraform state rm` the resource to get going again.

If this is intended behavior (I can't see a reason - which doesn't mean there isn't one), then maybe it should behave in a "delete+create (recreate)" - but this feels like a tough thing to do when _read_ fails.

**Comment by scottwinkler** [comment]
i understand the frustration, as I have experienced it a lot myself. the original reason for doing it, is that any change you make to the create/read/update/delete scripts fundamentally changes the behavior/state of the resource. It's as strict as it is in the hope that you would test resources thoroughly before using in production. That being said, it no longer appears to be useful. In fact, It appears I have already removed in from delete and update some time ago, because of the headache it caused.

I think removing ForceNew from read and create to be consistent is a good idea. Would you like to make a PR for this? it's an easy fix.

**Comment by mrzor** [comment]
Allright - I'm going to give this a shot. I have zero+epsilon experience with Go though.
